version: "3"
services:
  nginx-react:
    container_name: react-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
        NODE_ENV: production
